apiVersion: v1
kind: Service
metadata:
  name: employee-service                 #name of the service
  labels:
    app: employeeapp-service                    
spec:
  type : NodePort
  ports:
  - port: 9090
  selector:
    app: employeeapp              #selecting the pod with lable value  